# Generated by Django 3.2.2 on 2021-06-16 19:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=25)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idMatch', models.AutoField(primary_key=True, serialize=False)),
                ('homeGoals', models.PositiveSmallIntegerField(default=0)),
                ('guestGoals', models.PositiveSmallIntegerField(default=0)),
                ('startDate', models.DateTimeField()),
                ('finished_by_refree', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pesel', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(70999999999)])),
                ('firstName', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='Tylko litery')])),
                ('secondName', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='Tylko litery')])),
                ('position', models.CharField(choices=[('N', 'Napastnik'), ('BR', 'Bramkarz'), ('LP', 'Lewy pomocnik'), ('PP', 'Prawy pomocnik'), ('LS', 'Lewy skrzydlowy'), ('PS', 'Prawy skrzydlowy'), ('SO', 'Srodkowy obronca'), ('LO', 'Lewy obronca'), ('PO', 'Prawy obronca')], max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='Tylko litery')])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('statusHealth', models.CharField(choices=[('KO', 'Kontuzjowany'), ('ZD', 'Zdrowy'), ('RH', 'Rehabilitacja')], default='ZDROWY', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('idQueue', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_creation', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 6, 16))])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('id_trainer', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatsPlayerLeague',
            fields=[
                ('pesel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.player')),
                ('numberOfMinutes', models.PositiveIntegerField(default=0)),
                ('numberOfAssists', models.PositiveIntegerField(default=0)),
                ('numberOfGoals', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatsTeam',
            fields=[
                ('idTeam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.team')),
                ('numberOfGoalsLost', models.PositiveIntegerField(default=0)),
                ('numberOfGoalsScored', models.PositiveIntegerField(default=0)),
                ('numberOfMatchesWon', models.PositiveIntegerField(default=0)),
                ('numberOfDraws', models.PositiveIntegerField(default=0)),
                ('numberOfMatchesLost', models.PositiveIntegerField(default=0)),
                ('numberOfScores', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='id_trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.trainer'),
        ),
        migrations.CreateModel(
            name='StatsPlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfYellowCard', models.PositiveIntegerField(default=0)),
                ('numberOfGoals', models.PositiveIntegerField(default=0)),
                ('idMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='id_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guest', to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home', to='mainapp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='idQueue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.queue'),
        ),
        migrations.AddConstraint(
            model_name='statsplayermatch',
            constraint=models.UniqueConstraint(fields=('player', 'idMatch'), name='ZAWODNIK_MECZ'),
        ),
    ]
